<?php // controller for post success page...
// checks user logged in...
requireLogin();
// views...
include(VIEWS.'header.php');
include(VIEWS.'contentPostSuccess.php');
include(VIEWS.'footer.php');
?> 